[package]
name = "drop_cell_macros"
version = "0.0.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.47"
syn = { version = "1.0.103", features = ["extra-traits", "full" ] }
quote = "1.0.21"

